## Recipes

## Weapons
- type: latheRecipe
  id: WeaponDominator
  result: WeaponDominator
  categories:
  - Weapons
  completetime: 5
  materials:
    Steel: 750
    Plastic: 250
    Glass: 300
    Plasma: 100
    Gold: 100
    
- type: latheRecipe
  id: WeaponTaser
  result: WeaponTaser
  categories:
  - Weapons
  completetime: 8
  materials:
    Steel: 850
    Plastic: 1000
    Glass: 300
    Gold: 200
    Silver: 200
# Clothing

- type: latheRecipe
  id: PortableRechargerBag
  result: PortableRechargerBag
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 1500
    Plastic: 750
    Glass: 500
    Plasma: 500
    Gold: 300
    Silver: 150

- type: latheRecipe
  id: PortableRechargerTurbo
  result: PortableRechargerTurbo
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 1500
    Plastic: 750
    Glass: 500
    Plasma: 500
    Gold: 300
    Silver: 150

- type: latheRecipe
  id: PortableRechargerTurboBag
  result: PortableRechargerTurboBag
  categories:
  - Clothing
  completetime: 15
  materials:
    Steel: 2500
    Plastic: 1500
    Glass: 500
    Plasma: 1000
    Gold: 500
    Silver: 300
    Uranium: 150

- type: latheRecipe
  id: ClothingHeadHelmetFlash
  result: ClothingHeadHelmetFlash
  categories:
  - Clothing
  completetime: 5
  materials:
    Steel: 350
    Plastic: 200
    Glass: 150
    Plasma: 100
    Gold: 25

- type: latheRecipe
  id: ClothingNeckFlashNeck
  result: ClothingNeckFlashNeck
  categories:
  - Clothing
  completetime: 3
  materials:
    Steel: 400
    Plastic: 300
    Glass: 200
    Plasma: 300
    Uranium: 25
    
# Tools

- type: latheRecipe
  parent: BaseToolRecipe
  id: ExmFlash
  result: ExmFlash
  materials:
    Steel: 200
    Glass: 100
    Plastic: 200
    Plasma: 50